import { MenuItem, BranchInfo, GalleryPhoto, Testimonial } from "@/types";

export const BRAND_INFO = {
  name: "Pelita Cafe",
  legalName: "Pelita Heritage Sdn Bhd",
  tagline: "Fuel Your Day With Our Perfect Cup of Coffee",
  shortDescription: "Boutique coffee roasters & modern Malaysian culinary destination. Handcrafted brews, artisanal dishes, and warm community vibes.",
  whatsappNumber: "60123377807",
  whatsappUrl: "https://wa.me/60123377807?text=Hi%20Pelita%20Cafe%2C%20I%20would%20like%20to%20place%20an%20order%20or%20inquire%20about%20a%20table%20reservation.",
  email: "pelitaheritagesdnbhd@gmail.com",
  instagram: "https://www.instagram.com/pelitacafe.official/",
  facebook: "https://www.facebook.com/people/Pelita-Cafe/100064695456324/",
  logo: "/assets/images/logo.webp",
  logoWhite: "/assets/images/logo-white.webp",
  logoDark: "/assets/images/logo-dark.webp",
};

export const MENU_ITEMS: MenuItem[] = [
  // Signature Meals
  {
    id: "m-1",
    name: "Nasi Ayam Pelita",
    description: "Our crown signature tender marinated golden chicken served with fragrant heritage rice, house spicy sambal, crispy keropok, and rich soup.",
    category: "signature",
    price: "RM 16.90",
    image: "/assets/images/nasi-ayam-pelita.webp",
    isSignature: true,
    isPopular: true,
    badge: "House Signature",
  },
  {
    id: "m-2",
    name: "Nasi Ayam Geprek",
    description: "Crispy battered whole chicken thigh hand-smashed with fiery aromatic chili sambal geprek and served over hot jasmine rice.",
    category: "signature",
    price: "RM 17.50",
    image: "/assets/images/nasi-ayam-geprek.webp",
    isSpicy: true,
    isPopular: true,
    badge: "Spicy Favorite",
  },
  {
    id: "m-3",
    name: "Nasi Ayam Penyet",
    description: "Authentic slow-simmered spiced fried chicken pressed traditional style, paired with tempeh, tofu, fresh lalapan, and zesty sambal terasi.",
    category: "signature",
    price: "RM 17.50",
    image: "/assets/images/nasi-ayam-penyet.webp",
    isSpicy: true,
    isPopular: true,
  },
  {
    id: "m-4",
    name: "Nasi Lemak Sambal Sotong",
    description: "Fragrant santan coconut rice with tender wok-braised spiced calamari sambal, roasted peanuts, crunchy anchovies, cucumber & egg.",
    category: "allday",
    price: "RM 18.90",
    image: "/assets/images/nasi-lemak-sotong.webp",
    isSignature: true,
    isPopular: true,
    badge: "Chef's Special",
  },
  {
    id: "m-5",
    name: "Nasi Lemak Ayam Crispy",
    description: "Rich steamed pandan coconut rice accompanied by our secret spiced jumbo fried chicken, boiled egg, and slow-cooked caramelized sambal.",
    category: "allday",
    price: "RM 16.90",
    image: "/assets/images/nasi-lemak.webp",
    isPopular: true,
  },
  {
    id: "m-6",
    name: "Traditional Soto Ayam",
    description: "Aromatic turmeric herbal chicken broth infused with lemongrass and galangal, filled with shredded chicken, pressed rice cakes (nasi impit), and bergedil.",
    category: "allday",
    price: "RM 14.50",
    image: "/assets/images/soto-ayam.webp",
  },
  // Premium Coffee
  {
    id: "c-1",
    name: "Pelita Spanish Latte",
    description: "Double espresso pulled fresh over condensed sweet cream milk and velvety microfoam, balanced with rich cocoa undertones.",
    category: "coffee",
    price: "RM 13.90",
    image: "/assets/images/coffee.webp",
    isSignature: true,
    badge: "Best Seller",
    temperature: "Both",
  },
  {
    id: "c-2",
    name: "Artisan Buttercream Latte",
    description: "Rich cold-brew espresso topped with a luscious velvety handcrafted salted buttercream froth.",
    category: "coffee",
    price: "RM 14.90",
    image: "/assets/images/coffee/1.webp",
    isSignature: true,
    badge: "Trending",
    temperature: "Iced",
  },
  {
    id: "c-3",
    name: "Caramel Macchiato",
    description: "Layered steamed milk with vanilla infusion, marked with fresh espresso and drizzled with buttery caramel sauce.",
    category: "coffee",
    price: "RM 14.00",
    image: "/assets/images/coffee/2.webp",
    temperature: "Both",
  },
  {
    id: "c-4",
    name: "Classic Caffe Latte",
    description: "Espresso roast blend with silky steamed full cream milk, crowned with delicate latte art.",
    category: "coffee",
    price: "RM 11.90",
    image: "/assets/images/coffee/3.webp",
    temperature: "Both",
  },
  {
    id: "c-5",
    name: "Mocha Loca",
    description: "Harmonious union of single-origin dark Dutch cocoa with rich espresso shot and steamed milk.",
    category: "coffee",
    price: "RM 14.50",
    image: "/assets/images/coffee/4.webp",
    temperature: "Both",
  },
  // Wok Specialties
  {
    id: "w-1",
    name: "Nasi Goreng Pelita Chicken Wing",
    description: "Wok-tossed seasoned fried rice loaded with wok-hei aroma, topped with our signature marinated crispy chicken wing.",
    category: "wok",
    price: "RM 16.50",
    image: "/assets/images/dishes-spread.webp",
    isPopular: true,
    badge: "Wok Specialty",
  },
  {
    id: "w-2",
    name: "Kuey Teow Kungfu",
    description: "Flat rice noodles wok-charred and enveloped in an egg-rich savory prawn and squid gravy with garden greens.",
    category: "wok",
    price: "RM 15.50",
    image: "/assets/images/fried_dishes/4.webp",
  },
  {
    id: "w-3",
    name: "Nasi Goreng Kampung Cili Padi",
    description: "Traditional village-style fried rice infused with pounded shallots, bird’s eye chili, crispy water spinach (kangkung), and golden anchovies.",
    category: "wok",
    price: "RM 14.50",
    image: "/assets/images/fried_dishes/1.webp",
    isSpicy: true,
  },
  // Light Bites
  {
    id: "b-1",
    name: "Roti Bakar Kaya & Butter",
    description: "Thick-cut artisanal bread toasted crisp over flame, slathered with Hainanese fragrant coconut egg jam and cold butter slabs.",
    category: "bites",
    price: "RM 6.50",
    image: "/assets/images/dishes-spread.webp",
    isPopular: true,
  },
  {
    id: "b-2",
    name: "Crispy Cheese Loaded Fries",
    description: "Golden shoestring fries seasoned lightly with sea salt, generously smothered with melted cheddar cheese glaze.",
    category: "bites",
    price: "RM 11.00",
    image: "/assets/images/fried_dishes/3.webp",
  },
  {
    id: "b-3",
    name: "Golden Bakwan Sayur",
    description: "Traditional crispy mixed vegetable fritters served piping hot with sweet tangy homemade dipping sauce.",
    category: "bites",
    price: "RM 8.90",
    image: "/assets/images/fried_dishes/5.webp",
  }
];

export const BRANCHES: BranchInfo[] = [
  {
    id: "sepang",
    name: "Pelita Cafe Sepang",
    city: "Sepang, Selangor",
    tagline: "Our Original Heritage Flagship",
    address: "Medan 23, Bandar Baru Salak Tinggi",
    fullAddress: "Medan 23, Bandar Baru Salak Tinggi, 43900 Sepang, Selangor, Malaysia",
    phone: "+60123377807",
    displayPhone: "012-337 7807",
    hours: "Saturday – Thursday: 9:00 AM – 7:00 PM",
    closingDay: "Closed on Fridays",
    mapUrl: "https://maps.google.com/?q=Pelita+Cafe+Sepang+Medan+23+Salak+Tinggi",
    image: "/assets/images/cafe-interior.webp",
    features: ["Specialty Roastery", "Cozy Indoor Air-con", "Alfresco Terrace", "Surau Nearby", "Free High-Speed Wi-Fi"]
  },
  {
    id: "putrajaya",
    name: "Pelita Cafe Putrajaya",
    city: "Presint 15, Putrajaya",
    tagline: "Diplomatic Enclave Culinary Hub",
    address: "Jalan Diplomatik 1, Presint 15",
    fullAddress: "Jalan Diplomatik 1, Presint 15, 62050 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia",
    phone: "+60123377807",
    displayPhone: "012-337 7807",
    hours: "Saturday – Wednesday: 9:00 AM – 10:00 PM",
    closingDay: "Closed on Thursdays",
    mapUrl: "https://maps.google.com/?q=Pelita+Cafe+Putrajaya+Presint+15",
    image: "/assets/images/cafe-event.webp",
    features: ["Private Event Booking", "Evening Dinner Vibes", "Ample Street Parking", "Family Friendly Seating", "Catering Base"]
  }
];

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: "g-1",
    title: "Artisanal Coffee Craft",
    subtitle: "Precision extracted specialty beans roasted with passion",
    src: "/assets/images/coffee.webp",
    category: "coffee",
  },
  {
    id: "g-2",
    title: "Signature Nasi Ayam Pelita",
    subtitle: "A beloved recipe perfected over generations",
    src: "/assets/images/nasi-ayam-pelita.webp",
    category: "cuisine",
  },
  {
    id: "g-3",
    title: "Boutique Cafe Sanctuary",
    subtitle: "Sun-drenched interiors, warm tones, and calm corners",
    src: "/assets/images/cafe-interior.webp",
    category: "space",
  },
  {
    id: "g-4",
    title: "Celebrations & Gatherings",
    subtitle: "Hosting heartfelt reunions and memorable milestone dinners",
    src: "/assets/images/cafe-event.webp",
    category: "vibe",
  },
  {
    id: "g-5",
    title: "Velvety Spanish Latte",
    subtitle: "Double espresso kissed by velvety sweet milk",
    src: "/assets/images/coffee/1.webp",
    category: "coffee",
  },
  {
    id: "g-6",
    title: "Culinary Feast Spread",
    subtitle: "Traditional Malaysian spices meeting contemporary bistro flair",
    src: "/assets/images/dishes-spread.webp",
    category: "cuisine",
  },
  {
    id: "g-7",
    title: "Freshly Brewed Moments",
    subtitle: "The distinct aroma of freshly ground Arabica beans",
    src: "/assets/images/coffee/2.webp",
    category: "coffee",
  },
  {
    id: "g-8",
    title: "Craftsmanship & Heritage",
    subtitle: "Dedicated cooks honoring authentic cooking techniques",
    src: "/assets/images/chef-story.webp",
    category: "space",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t-1",
    author: "Zulhilmi Ariffin",
    role: "Regular Guest • Sepang",
    comment: "Pelita Cafe has redefined boutique dining around Salak Tinggi. The Spanish Latte has the perfect coffee-to-sweetness ratio, and their Nasi Ayam Pelita sambal is pure culinary magic.",
    rating: 5,
    branch: "Sepang Branch",
  },
  {
    id: "t-2",
    author: "Farah Nadia",
    role: "Putrajaya Resident",
    comment: "We booked Pelita Cafe Putrajaya for a family birthday event of 25 guests. The team was exceedingly courteous, dishes arrived piping hot, and the modern cozy atmosphere made everyone feel at home.",
    rating: 5,
    branch: "Putrajaya Branch",
  },
  {
    id: "t-3",
    author: "Khairul Anuar",
    role: "Coffee Aficionado",
    comment: "Finally, a place that takes their roast seriously while still serving comforting local wok food! The Buttercream Latte is sensational. Clean, polished, and top-tier hospitality.",
    rating: 5,
    branch: "Sepang Branch",
  },
  {
    id: "t-4",
    author: "Sharifah Sofia",
    role: "Event Planner",
    comment: "The aesthetic, customer care, and quick response time via WhatsApp made organizing our corporate brunch completely effortless. Highly recommended!",
    rating: 5,
    branch: "Putrajaya Branch",
  },
];

export const MENU_BOOK_PAGES = [
  "/assets/images/menu-book/page-1.jpg",
  "/assets/images/menu-book/page-2.jpg",
  "/assets/images/menu-book/page-3.jpg",
  "/assets/images/menu-book/page-4.jpg",
  "/assets/images/menu-book/page-5.jpg",
  "/assets/images/menu-book/page-6.jpg",
  "/assets/images/menu-book/page-7.jpg",
  "/assets/images/menu-book/page-8.jpg",
  "/assets/images/menu-book/page-9.jpg",
];
